### PR TITLE
Add ceph configuration for nvme/ssd storage

### PR DESCRIPTION
**Pull request by gitsridhar**
Add ceph config commands in fio automation script. This will setup
the ceph envionment to recognize nvme/ssd storage.

Signed-off-by: gitsridhar <svenkat@us.ibm.com>

### CODE REVIEW

**Comment by gitsridhar** [comment]
@lukebrowning Do not merge this yet. I am running fio automation with this change.

**Comment by gitsridhar** [comment]
@lukebrowning I have removed WIP from the title. The run completed for block and file is in progress now. This PR can be merged.

**Review by lukebrowning — COMMENTED** [review]
Please put this in a function, like I did with the other steps - create, install, run, etc, so that it can be commented out for debugging purposes.

**Comment by gitsridhar** [comment]
@lukebrowning I moved the code to a function.

**Review by lukebrowning — APPROVED** [review]

**Pull request merged**
