### PR TITLE
Add support for libvirt 6.0.0

### PR DESCRIPTION
**Pull request by lukebrowning**
The default behavior of libvirtd is changed as described here
https://bugzilla.redhat.com/show_bug.cgi?id=1750340.

Applications like ours are expected to change.  Basically, to
disable the new behavior which is to use systemd socket
activation.  The libvirtd --listen argument is ignored.  Our
application uses the --listen argument.

The changes that I have implemented disable this new libvirt
behavior, but it doesn't result in a clean run.  The ocp4-upi-kvm
project fails with this message.

null_resource.worker_info[1]: Creation complete after 0s [id=8269907842673180363]
null_resource.master_info[1]: Creation complete after 0s [id=1016957225698017199]
null_resource.worker_info[0]: Creating...
null_resource.worker_info[2]: Creating...
module.prepare.libvirt_pool.storage_pool: Creating...
null_resource.worker_info[2]: Creation complete after 0s [id=2203494823622858497]
null_resource.worker_info[0]: Creation complete after 0s [id=7485490152096873748]
module.prepare.libvirt_network.network: Creating...
module.prepare.libvirt_pool.storage_pool: Creation complete after 5s [id=a642ca6e-b387-48b2-b5dc-4770b97eee28]
module.prepare.libvirt_volume.bastion: Creating...
module.prepare.libvirt_volume.bastion: Creation complete after 1s [id=/home/libvirt/images/test-ocp4-6/test-ocp4-6-bastion-vol]

Error: Error creating libvirt network: virError(Code=89, Domain=47, Message='Message recipient disconnected from message bus without replying')

  on modules/1_prepare/prepare.tf line 36, in resource "libvirt_network" "network":
  36: resource "libvirt_network" "network" {

The libvirt problem comes into play as the new package is
included in the repo that updates rhel 8.2 even though it
was released in rhel 8.3.  The rhel repos are stacked, so
you always get the latest version in the latest rhel release.

Signed-off-by: Luke Browning <lukebrowning@us.ibm.com>

### CODE REVIEW

**Comment by bpradipt** [comment]
@lukebrowning how about keeping libvirt at a specific version and avoid updating it ?

**Comment by yussufsh** [comment]
From the BZ:
```
Thus if the mgmt app / admin wants to use TCP/TLS sockets they have two choices

  - To continue the old approach (setting --listen in /etc/sysconfig/libvirtd), then they MUST use 'systemctl mask ...' for all the socket units listed above, before libvirtd.service is started.

  - To adapt to use the new approach, then don't touch /etc/sysconfig/libvirtd at all. Instead use 'systemctl enable libvirtd-tls.socket && 'systemctl start libvirtd-tls.socket'   (assuming  TLS is desired).
```

@lukebrowning @gitsridhar did you try the 1st approach? It does not give me any error when the sockets are masked using older approach OR am I missing something?

**Comment by gitsridhar** [comment]
@yussufsh did you look at the commit and code changes Luke did?

**Comment by lukebrowning** [comment]
So I have made some progress.   The server that I was using I had never used before and it has very old firmware.   I updated the BMC and PNOR and that appears to have solved the problem in the libvirt terraform module.   I got an error message indicating a kvm power capability was not  set...

**Pull request merged**
